### ISSUE TITLE
Atlassian Cloud SOAP is deprecated, and specifying rest in the config does nothing

### ISSUE THREAD

**Issue by ziz** [alisaifee/jira-cli#19]
Using an Atlassian cloud instance, SOAP is no longer available, so we have to use rest.  Unfortunately, specifying rest in the config file does nothing, because in interface.py, the parser specifies a default of "soap" for the --protocol argument, and so this line:

```
protocol=post_args.protocol or config.protocol
```

always ignores config.protocol.  I suggest changing the parser default for --protocol to `None` and changing that line to:

```
protocol=post_args.protocol or config.protocol or "soap"
```

to maintain the current functionality, or

```
protocol=post_args.protocol or config.protocol or "rest"
```

to default to a more sane configuration now that JIRA is moving to prefer REST.

**Comment by alisaifee** [comment]
@ziz: thanks. Issue is resolved in `2.0.10` on pypi.
