### ISSUE TITLE
unable to set fixVersions field using jira-cli version 2

### ISSUE THREAD

**Issue by pguibert** [alisaifee/jira-cli#20]
unable to set fixVersions field using jira-cli version 2.
I tried to use --extra [EXTRA_FIELDS]
example:
--extra fixVersions="S5" WPXPRF-3816

but i faced some error:
data was not an array

is there more information about syntax to use ?

**Comment by alisaifee** [comment]
Hi @pguibert, the `extra` option in the update flow hasn't been tested much and will only really work for very few usecases (as the value is passed directly to the api). For `fixVersion` the api expects the `id` of the version being specified, wrapped in an array. 

If this functionality is required I think it would require explicit command line options to set the fix version and the affects versions fields.

**Comment by pguibert** [comment]
Hello Ali,
I agree with you to require explicit command line options.
This field is used by many users.

i would propose 2 optional commands to pass as arguments to jira-cli.
--fix-version-add <fixed_version_to_add>
--fix-version-del <fixed_version_to_delete>

If you agree with that specification,i can try to make you a proposal that you woul review after.
Not sure i will have time, but we can try like that.
would it be ok for you ?
BR,

**Comment by alisaifee** [comment]
Hi @pguibert. I've implemented something along those lines and the code is available in `master`. You can install and test if it works for you as follows:

```
pip install -e 'git+https://github.com/alisaifee/jira-cli@master#egg=jira-cli'
jira-cli --v2 update *issue-number* --fix-version=1.0 --fix-version=2.0
jira-cli --v2 update *issue-number* --affects-version=1.0 --affects-version=2.0
jira-cli --v2 update *issue-number* --remove-affects-version=2.0 --remove-fix-version=2.0
```

As I don't have a proper jira instance to test against, could I get your help to test this out additionally with the soap/rest protocol options (i.e. by adding the flags `--protocol=rest` and `protocol=soap` explicitly) before I make a release with this change?

**Comment by pguibert** [comment]
Hello Ali,
good news, since i could test the two changes that you brought.
now it is possible to set and unset values inside fix-version and affect-version fields.

I also could do some testing with soap too.

jira-cli --v2 update -u user -p pass --protocol rest --jira-url http://jira WPXPRF-3816 --fix-version=S4 --fix-version=S5
jira-cli --v2 update -u user -p pass --protocol rest --jira-url http://jira WPXPRF-3816 --remove-fix-version=S4
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --remove-fix-version=S5 
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --affects-version=S5
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --affects-version=S5 --affects-version=S4
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --affects-version=S5 --remove-affects-version=S4
jira-cli --v2 update -u user -p pass --protocol rest --jira-url http://jira WPXPRF-3816  --remove-affects-version=S5
jira-cli --v2 update -u user -p pass --protocol rest --jira-url http://jira WPXPRF-3816  --remove-affects-version=S766
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --affects-version=S5 --affects-version=S4666
jira-cli --v2 update -u user -p pass --protocol soap --jira-url http://jira WPXPRF-3816 --affects-version=S5 

thanks a lot. jira-cli api is more friendly than the below python jira api.

Just a question. It seems not obvious to be able to implement something without having the jira server. I mean, in order to implement it, how did you know that those fields were configurable in that way ? just documentation ? 

BR,
Philippe

**Comment by alisaifee** [comment]
Thanks for the additional tests, @pguibert. I'll make the release shortly.
