### ISSUE TITLE
Feature request: add --component or generic field inputs

### ISSUE THREAD

**Issue by jmmills** [alisaifee/jira-cli#25]
Multi-component projects often have component as a required field, it would be nice to be able to provide this via the "new" verb.
It could be done generically with a --field-$name=$value type argument.

**Comment by alisaifee** [comment]
Thanks. I like the idea of having generic fields passed in while creating new issues. Some fields however (for example, `components`) require a translation step before submitting to the jira api. I'll implement the `--component` argument first and then see how the generic `--field-$name` argument can be added.

**Comment by alisaifee** [comment]
`--component` argument for creating issues is now available in `2.0.15`
