### ISSUE TITLE
Does nothing unless --v2 is specified or added to the config

### ISSUE THREAD

**Issue by drennalls** [alisaifee/jira-cli#30]
The docs say to use `--v2` if desired but I find the cli simply returns (and does nothing) unless it is specified or `v2 = True` is added to `~/.jira-cli/config.cfg`. In my case "old_main" is never called and instead ends up in this block https://github.com/alisaifee/jira-cli/blob/master/jiracli/interface.py#L256

```
$ pip list | grep jira
jira (1.0.3)
jira-cli (2.0.17)
```

**Comment by alisaifee** [comment]
`v2` will be made the default and I will mostly drop support for the `old_main` in the next release
