### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by matthewferguson694** [alisaifee/jira-cli#40]
Hi guys,

I was wondering is it possible to add data into custom fields?

For example:

```
customfield_10004: Story Points is required.
```

**Comment by alisaifee** [comment]
Hi @matthewferguson694, yes it is possible (though not through the most user friendly method).

```
jira-cli new ..... --extra="customfield_10004=10"
```

You'll have to update to the latest version (`2.1.5`) though, as there was a recent regression that had broken the extra fields functionality

**Comment by matthewferguson694** [comment]
I was looking through your tagged releases, and the most recent is 2.1.4? :(

**Comment by alisaifee** [comment]
ah sorry about that - i've already updated pypi with the latest version, forgot to push the tag to github :)
