### ISSUE TITLE
Blank descriptions

### ISSUE THREAD

**Issue by michelts** [alisaifee/jira-cli#47]
To create an issue, if I don't specify a description, jiracli opens the default editor to fill it. I can leave it blank, but I need to do it through editor.

What do you think about deal with the description arg and ignore him if set to a blank string, or even better, what do you think about an option --no-description that simply avoid the editor in the lack of description?

I can help writting a PR, but I wan't to know if you approve the approach before develop it.

Thanks!

**Comment by alisaifee** [comment]
I think thats a valid requirement - in fact I myself get annoyed with having to go through the editor when I don't want to add a description yet. I'm happy to take a PR (I feel the approach of an explicit empty string, over the `--no-description` one might be more consistent)

**Comment by michelts** [comment]
Done! Sorry the late contribution ;)
