### ISSUE TITLE
Make a ticket unassigned

### ISSUE THREAD

**Issue by spapanik** [alisaifee/jira-cli#52]
I'm trying to unassign a ticket, and I tried:

jira-cli update FES-3190 --assign=""        
jira-cli update FES-3190 --assign="unassigned"

but with no success

**Comment by spapanik** [comment]
I've found that `--assign="-1"` unassigns the ticket.

**Comment by alisaifee** [comment]
I guess that a hidden feature of the jira api. If the functionality is needed enough though we could add an `--unassign`
